version: '3.9'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            postgres:
                condition: service_healthy
        restart: always
        env_file:
            - .env
        ports:
            - '3000:3000'
        command: >
            sh -c "npm run migration:run && npm run start:prod"

    postgres:
        image: postgres:17.0-alpine
        ports:
            - 5432:5432
        volumes:
            - ~/apps/postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=admin
            - POSTGRES_USER=admin
            - POSTGRES_DB=tiny_url
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -d tiny_url -U admin']
            interval: 5s
            timeout: 5s
            retries: 5
