version: '3.9'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - postgres
        restart: always
        env_file:
            - .env
        ports:
            - '3000:3000'
        entrypoint: >
            sh -c "./wait-for-it.sh postgres:5432 --timeout=30 --strict -- npm run migration:run && npm run start:dev"

    postgres:
        image: postgres:17.0-alpine
        ports:
            - 5432:5432
        volumes:
            - ~/apps/postgres:/var/lib/postgresql/data
        env_file:
            - .env
        environment:
            - POSTGRES_USER=${DATABASE_USERNAME}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - POSTGRES_DB=${DATABASE_NAME}
