import { applyDecorators } from '@nestjs/common';
import { ApiOperation, ApiBearerAuth, ApiOkResponse } from '@nestjs/swagger';
import { GetUserUrlsResponseDTO } from '../dtos/get-user-urls.res.dto';
import { ApiUnauthorizedDecorator } from '@shared/decorators/api-unauthorized.decorator';

export function ApiGetUserUrls() {
    return applyDecorators(
        ApiUnauthorizedDecorator(),
        ApiOperation({
            summary: 'Get User URLs',
            description: 'Retrieves an array of URLs generated by the user.',
        }),
        ApiOkResponse({ type: GetUserUrlsResponseDTO }),
        ApiBearerAuth()
    );
}
